
- hosts: all
  # any_errors_fatal: true
  # gather_facts: no
  # become: true
  tasks:

    - name: Ensure wget is installed
      become: true
      apt:
        name: wget
        state: present

    - name: Check for essentials
      include_role:
        name: check

    - name: Check hostname restrictions
      include_role:
        name: check
        tasks_from: check-host

- hosts: workers
  # remote_user: james
  tasks:
  - name: Simple connection test
    ansible.builtin.ping:
    #remote_user: james
  - name: run a simple command
    ansible.builtin.shell: /bin/ls -al /nonexistent
    ignore_errors: True
