
- hosts: all
  # any_errors_fatal: true
  # gather_facts: no
  # become: true
  tasks:

    - name: Ensure wget is installed
      become: true
      apt:
        name: wget
        state: present

    - name: Check for essentials
      include_role:
        name: check

